### ISSUE TITLE
Pandas is dependent and requires different versions

### ISSUE THREAD

**Issue by HakunanMatatat** [mobigroup/gmtsar#102]
In the following example:
https://colab.research.google.com/drive/1TARVTB7z8goZyEVDRWyTAKJpyuqZxzW2?usp=sharing#scrollTo=-FB-xXixURYm

dask-image 2023.8.1 requires pandas>=2.0.0, but you have pandas 1.5.3 which is incompatible.
pygmtsar 2024.2.15.post4 requires pandas>=2.2, but you have pandas 1.5.3 which is incompatible.

bigframes 0.20.1 requires pandas<2.1.4,>=1.5.0, but you have pandas 2.2.0 which is incompatible.
google-colab 1.0.0 requires pandas==1.5.3, but you have pandas 2.2.0 which is incompatible.

hi，How to fix it?

**Comment by AlexeyPechnikov** [comment]
You might ignore such notices because Google Colab maintains its own cache of Python libraries with specific versions. Google admins sometimes upgrade the packages in the cache, but you cannot influence it. When you try to reinstall another version of an installed package that is loaded by default, it requires restarting the processing kernel, which can be a hassle for users.
