### ISSUE TITLE
[Help]: "Look" functions

### ISSUE THREAD

**Issue by teagamrs** [mobigroup/gmtsar#158]
Hi Alexey,

could you please enlighten me about the differences between singlelook function (sbas.compute_interferogram_singlelook) and multilook function (sbas.compute_interferogram_multilook)? Should I use them together (like one after the other)? Or should I prefer one over the other? If yes, based on what kind of analysis/spatial resolution/higher or lower AOI?

Thank you very much!

**Comment by AlexeyPechnikov** [comment]
These functions are user-friendly wrappers around the `compute_interferogram()` function, designed for SBAS and PSI processing. Typically, multi-looking is used for SBAS and single-looking for PSI analysis, although this is not mandatory. In other words, multi-looking is more effective for distributed scatterers, while single-looking is better suited for persistent scatterers. 

Note that when using weighted interferogram processing (i.e., applying `psfunction`), it is possible to apply multi-looking even in PSI analysis because unstable pixel phases are suppressed in this manner.

```
# single-look interferogram processing has a limited set of arguments
# resolution and coarsen are not applicable here
def compute_interferogram_singlelook(self, pairs, name, weight=None, phase=None, wavelength=None, method='nearest', psize=None,
                                     stack=None, queue=16, timeout=None,
                                     skip_exist=False, joblib_backend=None, debug=False):
    self.compute_interferogram(pairs, name, weight=weight, phase=phase, method=method, wavelength=wavelength,
                               psize=psize, stack=stack, queue=queue, timeout=timeout,
                               skip_exist=skip_exist, joblib_backend=joblib_backend, debug=debug)

# For multilooking interferogram we can use square grid always using coarsen = (1,4)
def compute_interferogram_multilook(self, pairs, name, resolution=None, weight=None, phase=None, method='nearest',
                                    wavelength=None, psize=None, coarsen=(1,4), stack=None, queue=16, timeout=None,
                                    skip_exist=False, joblib_backend=None, debug=False):
    self.compute_interferogram(pairs, name, resolution=resolution, weight=weight, phase=phase, method=method,
                               wavelength=wavelength, psize=psize, coarsen=coarsen, stack=stack, queue=queue, timeout=timeout,
                               skip_exist=skip_exist, joblib_backend=joblib_backend, debug=debug)
```

**Comment by teagamrs** [comment]
Thank you Alexey!
