### ISSUE TITLE
[Help]: Low CPU utilization during sbas_parallel

### ISSUE THREAD

**Issue by SteffanDavies** [mobigroup/gmtsar#47]
I have been trying different combinations of settings for sbas_parallel on large grids. However, cpu utilization doesn't exceed aprox 3-4% on 128 cpu machine.

CPU: 128
RAM: 500GB
Swap: 200GB
SSD: ~4 GBPS R/W

Using chunksize of 2048 exploded memory and swap, reducing chunk size to 512 helps keep memory manageable.

![image](https://github.com/mobigroup/gmtsar/assets/50405969/cb78f60f-f413-4bf8-971f-79eea95bfd04)

![image](https://github.com/mobigroup/gmtsar/assets/50405969/2e7244cb-2459-4e96-a152-3fe6c5dfc665)

![image](https://github.com/mobigroup/gmtsar/assets/50405969/6e09ddc0-3e30-4fcd-b19d-1254215b5f51)

![image](https://github.com/mobigroup/gmtsar/assets/50405969/10713a42-e16f-447d-b59f-9561f5fcc7f9)

Changing Dask setup (num_workers=1 / num_workers=32) makes little difference.

**Comment by SteffanDavies** [comment]
Ajusting chunksize to 1024 helps, with average cpu around 25%.

![image](https://github.com/mobigroup/gmtsar/assets/50405969/4e7a1113-9b9a-48f6-9eea-9e9586a07d10)

![image](https://github.com/mobigroup/gmtsar/assets/50405969/b1a69509-dd72-4dd4-a55c-86eb7cf5266d)

So now sbas_parallel time is reduced from 9 hours to 15 minutes...

I gave your PyGMTSAR draft a quick read. You refer the issue of pixel wise memory requirements for deep arrays with larger chunksizes. You also refer to PyGMTSAR having built-in tools for estimating memory requirements of operations. I'm curious what these tools are considering in your examples you either let dask attribute number of workers automatically or in your large SBAS example set the workers to 1 due to insufficient memory per core. Also you select 512 or 1024 chunksize depending on grids but there is no sign of such automatic memory management that is obvious to the reader. Your code uses user defined datagrid.chunksize when chunksize=None... Can you explain?

**Comment by mobigroup** [comment]
Yes, 1024 is a reasonable amount and is recommended for large Docker image examples. The Dask dashboard provides useful information about processing health. Having too many chunks is not manageable, while processing excessively large chunks is unstable. This instability occurs because the available memory is shared among all the processes, and we need to ensure that each process has sufficient RAM at all times.

You can find the memory adjustment for a 3D datacube here: https://github.com/mobigroup/gmtsar/blob/pygmtsar/pygmtsar/pygmtsar/SBAS_sbas.py#L237-L242. Approximately, it is always advisable to have 2GB RAM per core for the default chunk size (512), and this is typically enough to have 4GB RAM for the larger recommended chunk size (1024).

Setting 'n_workers=1' will still use all cores (Total threads: 4) and allow the system to operate stably without swapping. We encounter inconsistencies when using Dask process management and joblib together, but this is unavoidable. High-memory-consumption GMTSAR binaries must be called, and Dask cannot manage the memory used by these tools.

**Comment by SteffanDavies** [comment]
From what I can remember your large stack example uses only 2 years of data, I would assume longer time series (5-7 years) would require more than 4GB per core for pixel wise operations using 1024 chunks,  is this correct? And that is why you have custom core for "minichunks".

2048 chunks in sbas will cause the system to run out of memory and use swap, slowing the disk down severely.due to high IO and high concurrency. Ideally avoiding swap altogether is preferable, however it is hard to find a good balance for high CPU machines.

**Comment by mobigroup** [comment]
In the draft, I provided examples using 2000 and 1000 interferograms. As you can see in the linked code, the SBAS datacube chunk sizes decrease as the set of pairs increases.

**Comment by SteffanDavies** [comment]
Also for some computations (corr_stack etc.) setting chunksise to auto is even faster than 1024, as dask will allocate approx 100mb per chunk. I usually change it back to 512/1024 just before unwrapping.

**Comment by SteffanDavies** [comment]
> In the draft, I provided examples using 2000 and 1000 interferograms. As you can see in the linked code, the SBAS datacube chunk sizes decrease as the set of pairs increases.

I look forward to reading the whole publication. It is good material for good software.

**Comment by mobigroup** [comment]
> 25% utilisation is really a waste of resources.

You should attempt to balance the number of workers and threads. Also, Dask can use custom memory allocators, which can be extremely helpful, but these depend heavily on your platform, OS, and even the specific version of the OS.

**Comment by mobigroup** [comment]
New version on GitHub uses default chunk size 1024 so you don’t need to change it anymore. I hope I’ve resolved all the issues to use the large enough chunk size on low-memory hosts.
