### ISSUE TITLE
[Bug]: No such file or directory: 'gmtsar_sharedir.csh'

### ISSUE THREAD

**Issue by ashman17** [mobigroup/gmtsar#53]
**Describe the bug**
I am following the Kumamoto Earthquake Colab but on my local system (MacOS BigSur). I have downloaded the dataset and all cells work well till the cell that executes `sbas.download_dem()` I get the following error with this code line:

```
File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/subprocess.py", line 1845, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'gmtsar_sharedir.csh'
```
(detailed error log below)

**System and software version:**
 - OS: MacOS BigSur Version 11.7.7
 - GMTSAR version: 

**Processing Log**

```
Downloading S1A_OPER_AUX_POEORB_OPOD_20210311T113922_V20160407T225943_20160409T005943.EOF: 100%|█| 4.41M/4.41M [00:01<00:
Downloading products: 100%|███████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.95s/product]
Downloading products: 100%|███████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  2.72product/s]
Downloading products: 100%|███████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  2.58product/s]
Downloading S1A_OPER_AUX_POEORB_OPOD_20210311T153048_V20160419T225943_20160421T005943.EOF: 100%|█| 4.41M/4.41M [00:02<00:
Downloading products: 100%|███████████████████████████████████████████████████████████| 1/1 [00:03<00:00,  3.53s/product]
Downloading products: 100%|███████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  2.59product/s]
Downloading products: 100%|███████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  2.73product/s]
Traceback (most recent call last):
  File "/Users/apple/Desktop/IIRS/sample.py", line 59, in <module>
    sbas.download_dem(backend="GMT")
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pygmtsar/SBAS_dem.py", line 50, in download_dem
    return self.download_dem_gmt(**kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pygmtsar/SBAS_dem_gmt_gdal.py", line 47, in download_dem_gmt
    gmtsar_sharedir = PRM().gmtsar_sharedir()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pygmtsar/PRM_gmtsar.py", line 17, in gmtsar_sharedir
    p = subprocess.Popen(argv, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/subprocess.py", line 969, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/subprocess.py", line 1845, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'gmtsar_sharedir.csh'
```

**Comment by mobigroup** [comment]
The utility gmtsar_sharedir.csh is from GMTSAR software package. Install GMTSAR binaries following the section “Install PyGMTSAR Python library on MacOS (Apple Silicon and Intel)” in PyGMTSAR documentation: https://mobigroup.github.io/gmtsar/ Alternatively, you can refer to PyGMTSAR continuous integration (CI) tests where MacOS installation commands included: https://github.com/mobigroup/gmtsar/blob/pygmtsar/.github/workflows/macos.yml

**Comment by NMoghaddam** [comment]
I run "PyGMTSAR_Türkiye_Earthquakes_2023_01_29_2023_02_10_2scenes.ipynb" on a Windows machine and Google Colab today, and received the error when building GMTSAR in cell2. Surprisingly, it wasn't the case yesterday. 


`collect2: error: ld returned 1 exit status
make[2]: *** [Makefile:10: make_slc_gf3] Error 1
make[1]: *** [Makefile:10: all] Error 2
/usr/bin/ld: ../../../gmtsar/libgmtsar.a(utils.o):(.bss+0x30): multiple definition of `debug'; ../../../gmtsar/libgmtsar.a(sio_struct.o):(.bss+0x30): first defined here
/usr/bin/ld: ../../../gmtsar/libgmtsar.a(utils.o):(.bss+0x34): multiple definition of `verbose'; ../../../gmtsar/libgmtsar.a(sio_struct.o):(.bss+0x34): first defined here
/usr/bin/ld: ../../../gmtsar/libgmtsar.a(utils.o):(.bss+0x0): multiple definition of `SAR_mode'; ../../../gmtsar/libgmtsar.a(sio_struct.o):(.bss+0x0): first defined here
/usr/bin/ld: ../../../gmtsar/libgmtsar.a(utils.o):(.bss+0x8): multiple definition of `forced_slope'; ../../../gmtsar/libgmtsar.a(sio_struct.o):(.bss+0x8): first defined here
/usr/bin/ld: ../../../gmtsar/libgmtsar.a(utils.o):(.bss+0x10): multiple definition of `quiet_flag'; ../../../gmtsar/libgmtsar.a(sio_struct.o):(.bss+0x10): first defined here
/usr/bin/ld: ../../../gmtsar/libgmtsar.a(utils.o):(.bss+0x14): multiple definition of `nodata'; ../../../gmtsar/libgmtsar.a(sio_struct.o):(.bss+0x14): first defined here
/usr/bin/ld: ../../../gmtsar/libgmtsar.a(utils.o):(.bss+0x18): multiple definition of `sio_flag'; ../../../gmtsar/libgmtsar.a(sio_struct.o):(.bss+0x18): first defined here
/usr/bin/ld: ../../../gmtsar/libgmtsar.a(utils.o):(.bss+0x1c): multiple definition of `roi_flag'; ../../../gmtsar/libgmtsar.a(sio_struct.o):(.bss+0x1c): first defined here
/usr/bin/ld: ../../../gmtsar/libgmtsar.a(utils.o):(.bss+0x20): multiple definition of `dopp'; ../../../gmtsar/libgmtsar.a(sio_struct.o):(.bss+0x20): first defined here
/usr/bin/ld: ../../../gmtsar/libgmtsar.a(utils.o):(.bss+0x24): multiple definition of `force_slope'; ../../../gmtsar/libgmtsar.a(sio_struct.o):(.bss+0x24): first defined here
/usr/bin/ld: ../../../gmtsar/libgmtsar.a(utils.o):(.bss+0x28): multiple definition of `quad_pol'; ../../../gmtsar/libgmtsar.a(sio_struct.o):(.bss+0x28): first defined here
/usr/bin/ld: ../../../gmtsar/libgmtsar.a(utils.o):(.bss+0x2c): multiple definition of `swap'; ../../../gmtsar/libgmtsar.a(sio_struct.o):(.bss+0x2c): first defined here
/usr/bin/ld: ../../../gmtsar/libgmtsar.a(plxyz.o):(.bss+0x0): multiple definition of `SAR_mode'; ../../../gmtsar/libgmtsar.a(sio_struct.o):(.bss+0x0): first defined here
/usr/bin/ld: ../../../gmtsar/libgmtsar.a(plxyz.o):(.bss+0x8): multiple definition of `forced_slope'; ../../../gmtsar/libgmtsar.a(sio_struct.o):(.bss+0x8): first defined here
/usr/bin/ld: ../../../gmtsar/libgmtsar.a(plxyz.o):(.bss+0x10): multiple definition of `quiet_flag'; ../../../gmtsar/libgmtsar.a(sio_struct.o):(.bss+0x10): first defined here
/usr/bin/ld: ../../../gmtsar/libgmtsar.a(plxyz.o):(.bss+0x14): multiple definition of `nodata'; ../../../gmtsar/libgmtsar.a(sio_struct.o):(.bss+0x14): first defined here
/usr/bin/ld: ../../../gmtsar/libgmtsar.a(plxyz.o):(.bss+0x18): multiple definition of `sio_flag'; ../../../gmtsar/libgmtsar.a(sio_struct.o):(.bss+0x18): first defined here
/usr/bin/ld: ../../../gmtsar/libgmtsar.a(plxyz.o):(.bss+0x1c): multiple definition of `roi_flag'; ../../../gmtsar/libgmtsar.a(sio_struct.o):(.bss+0x1c): first defined here
/usr/bin/ld: ../../../gmtsar/libgmtsar.a(plxyz.o):(.bss+0x20): multiple definition of `dopp'; ../../../gmtsar/libgmtsar.a(sio_struct.o):(.bss+0x20): first defined here
/usr/bin/ld: ../../../gmtsar/libgmtsar.a(plxyz.o):(.bss+0x24): multiple definition of `force_slope'; ../../../gmtsar/libgmtsar.a(sio_struct.o):(.bss+0x24): first defined here
/usr/bin/ld: ../../../gmtsar/libgmtsar.a(plxyz.o):(.bss+0x28): multiple definition of `quad_pol'; ../../../gmtsar/libgmtsar.a(sio_struct.o):(.bss+0x28): first defined here
/usr/bin/ld: ../../../gmtsar/libgmtsar.a(plxyz.o):(.bss+0x2c): multiple definition of `swap'; ../../../gmtsar/libgmtsar.a(sio_struct.o):(.bss+0x2c): first defined here
/usr/bin/ld: ../../../gmtsar/libgmtsar.a(plxyz.o):(.bss+0x30): multiple definition of `debug'; ../../../gmtsar/libgmtsar.a(sio_struct.o):(.bss+0x30): first defined here
/usr/bin/ld: ../../../gmtsar/libgmtsar.a(plxyz.o):(.bss+0x34): multiple definition of `verbose'; ../../../gmtsar/libgmtsar.a(sio_struct.o):(.bss+0x34): first defined here
collect2: error: ld returned 1 exit status
make[2]: *** [Makefile:10: make_slc_nsr] Error 1
make[1]: *** [Makefile:10: all] Error 2
make: *** [Makefile:49: install-preproc] Error 2`

**Comment by NMoghaddam** [comment]
So, running two notebooks today I am getting two different errors:
The first one is with the `GMTSAR` build in cell 2 [ this error is unstable] and the second one is when I would like to run the `sbas.download_dem()`. I am on windows machine and just opened the notebook through the link here: https://github.com/mobigroup/gmtsar . 

The errors that I am getting are:

**GMTSAR** 
`collect2: error: ld returned 1 exit status
make[2]: *** [Makefile:10: make_slc_gf3] Error 1
make[1]: *** [Makefile:10: all] Error 2
/usr/bin/ld: ../../../gmtsar/libgmtsar.a(utils.o):(.bss+0x30): multiple definition of `debug'; ../../../gmtsar/libgmtsar.a(sio_struct.o):(.bss+0x30): first defined here
/usr/bin/ld: ../../../gmtsar/libgmtsar.a(utils.o):(.bss+0x34): multiple definition of `verbose'; ../../../gmtsar/libgmtsar.a(sio_struct.o):(.bss+0x34): first defined here
/usr/bin/ld: ../../../gmtsar/libgmtsar.a(utils.o):(.bss+0x0): multiple definition of `SAR_mode'; ../../../gmtsar/libgmtsar.a(sio_struct.o):(.bss+0x0): first defined here
/usr/bin/ld: ../../../gmtsar/libgmtsar.a(utils.o):(.bss+0x8): multiple definition of `forced_slope'; ../../../gmtsar/libgmtsar.a(sio_struct.o):(.bss+0x8): first defined here
/usr/bin/ld: ../../../gmtsar/libgmtsar.a(utils.o):(.bss+0x10): multiple definition of `quiet_flag'; ../../../gmtsar/libgmtsar.a(sio_struct.o):(.bss+0x10): first defined here
/usr/bin/ld: ../../../gmtsar/libgmtsar.a(utils.o):(.bss+0x14): multiple definition of `nodata'; ../../../gmtsar/libgmtsar.a(sio_struct.o):(.bss+0x14): first defined here
/usr/bin/ld: ../../../gmtsar/libgmtsar.a(utils.o):(.bss+0x18): multiple definition of `sio_flag'; ../../../gmtsar/libgmtsar.a(sio_struct.o):(.bss+0x18): first defined here
/usr/bin/ld: ../../../gmtsar/libgmtsar.a(utils.o):(.bss+0x1c): multiple definition of `roi_flag'; ../../../gmtsar/libgmtsar.a(sio_struct.o):(.bss+0x1c): first defined here
/usr/bin/ld: ../../../gmtsar/libgmtsar.a(utils.o):(.bss+0x20): multiple definition of `dopp'; ../../../gmtsar/libgmtsar.a(sio_struct.o):(.bss+0x20): first defined here
/usr/bin/ld: ../../../gmtsar/libgmtsar.a(utils.o):(.bss+0x24): multiple definition of `force_slope'; ../../../gmtsar/libgmtsar.a(sio_struct.o):(.bss+0x24): first defined here
/usr/bin/ld: ../../../gmtsar/libgmtsar.a(utils.o):(.bss+0x28): multiple definition of `quad_pol'; ../../../gmtsar/libgmtsar.a(sio_struct.o):(.bss+0x28): first defined here
/usr/bin/ld: ../../../gmtsar/libgmtsar.a(utils.o):(.bss+0x2c): multiple definition of `swap'; ../../../gmtsar/libgmtsar.a(sio_struct.o):(.bss+0x2c): first defined here
/usr/bin/ld: ../../../gmtsar/libgmtsar.a(plxyz.o):(.bss+0x0): multiple definition of `SAR_mode'; ../../../gmtsar/libgmtsar.a(sio_struct.o):(.bss+0x0): first defined here
/usr/bin/ld: ../../../gmtsar/libgmtsar.a(plxyz.o):(.bss+0x8): multiple definition of `forced_slope'; ../../../gmtsar/libgmtsar.a(sio_struct.o):(.bss+0x8): first defined here
/usr/bin/ld: ../../../gmtsar/libgmtsar.a(plxyz.o):(.bss+0x10): multiple definition of `quiet_flag'; ../../../gmtsar/libgmtsar.a(sio_struct.o):(.bss+0x10): first defined here
/usr/bin/ld: ../../../gmtsar/libgmtsar.a(plxyz.o):(.bss+0x14): multiple definition of `nodata'; ../../../gmtsar/libgmtsar.a(sio_struct.o):(.bss+0x14): first defined here
/usr/bin/ld: ../../../gmtsar/libgmtsar.a(plxyz.o):(.bss+0x18): multiple definition of `sio_flag'; ../../../gmtsar/libgmtsar.a(sio_struct.o):(.bss+0x18): first defined here
/usr/bin/ld: ../../../gmtsar/libgmtsar.a(plxyz.o):(.bss+0x1c): multiple definition of `roi_flag'; ../../../gmtsar/libgmtsar.a(sio_struct.o):(.bss+0x1c): first defined here
/usr/bin/ld: ../../../gmtsar/libgmtsar.a(plxyz.o):(.bss+0x20): multiple definition of `dopp'; ../../../gmtsar/libgmtsar.a(sio_struct.o):(.bss+0x20): first defined here
/usr/bin/ld: ../../../gmtsar/libgmtsar.a(plxyz.o):(.bss+0x24): multiple definition of `force_slope'; ../../../gmtsar/libgmtsar.a(sio_struct.o):(.bss+0x24): first defined here
/usr/bin/ld: ../../../gmtsar/libgmtsar.a(plxyz.o):(.bss+0x28): multiple definition of `quad_pol'; ../../../gmtsar/libgmtsar.a(sio_struct.o):(.bss+0x28): first defined here
/usr/bin/ld: ../../../gmtsar/libgmtsar.a(plxyz.o):(.bss+0x2c): multiple definition of `swap'; ../../../gmtsar/libgmtsar.a(sio_struct.o):(.bss+0x2c): first defined here
/usr/bin/ld: ../../../gmtsar/libgmtsar.a(plxyz.o):(.bss+0x30): multiple definition of `debug'; ../../../gmtsar/libgmtsar.a(sio_struct.o):(.bss+0x30): first defined here
/usr/bin/ld: ../../../gmtsar/libgmtsar.a(plxyz.o):(.bss+0x34): multiple definition of `verbose'; ../../../gmtsar/libgmtsar.a(sio_struct.o):(.bss+0x34): first defined here
collect2: error: ld returned 1 exit status
make[2]: *** [Makefile:10: make_slc_nsr] Error 1
make[1]: *** [Makefile:10: all] Error 2
make: *** [Makefile:49: install-preproc] Error 2`

**Download DEM**
`---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
[<ipython-input-25-05a7aaaf601a>](https://localhost:8080/#) in <cell line: 1>()
----> 1 sbas.download_dem(backend='GMT', resolution_meters=RESOLUTION)

4 frames
[/usr/lib/python3.10/subprocess.py](https://localhost:8080/#) in _execute_child(self, args, executable, preexec_fn, close_fds, pass_fds, cwd, env, startupinfo, creationflags, shell, p2cread, p2cwrite, c2pread, c2pwrite, errread, errwrite, restore_signals, gid, gids, uid, umask, start_new_session)
   1843                     if errno_num != 0:
   1844                         err_msg = os.strerror(errno_num)
-> 1845                     raise child_exception_type(errno_num, err_msg, err_filename)
   1846                 raise child_exception_type(err_msg)
   1847 

FileNotFoundError: [Errno 2] No such file or directory: 'gmtsar_sharedir.csh'`

Could it be due to recent updates happened yesterday?

**Comment by mobigroup** [comment]
Thanks, now the problem is apparent - Google Colab GCC compiler is upgraded recently, but GMTSAR source codes are not updated for years and cannot be compiled by modern GCC. We can resolve it using an old GCC compiler before version 10 (I think the key change is that gcc 10+ defaults to -fno-common instead of -fcommon, but maybe some other issues exist). I’ve updated Google Colab notebooks accordingly. I'm going to exclude GMTSAR tools usage in the future to prevent a lot of issues.

**Comment by NMoghaddam** [comment]
Thank you for updating the notebooks. Just have a question about these updates. Has this update also been implemented on the docker image or any part of the source code in the GitHub repo?

**Comment by mobigroup** [comment]
Docker images include pre-installed environment and these are not affected. There are no code changes but only installation commands updated in the notebooks.
