### ISSUE TITLE
[Help]: Detrending - fit_coords

### ISSUE THREAD

**Issue by SteffanDavies** [mobigroup/gmtsar#56]
Could you please explain what this option does exactly? Is it deramping?

**Comment by mobigroup** [comment]
The term "fit_coords" refers to linear deramping based on coordinates. Using the detrending function, we can eliminate the average value, the linear trend, and the component that is proportional to elevation. These details have been discussed multiple times in GMTSAR tickets, but there has been no implementation so far. By the way, I have also attempted to fit square and cubic topography components, as suggested in some papers, but the results have not been satisfactory.

Personally, I prefer using Gaussian high-pass or band-pass filtering, where we work with a reference frequency instead of a "reference point". It's important to note that we already apply low-pass filtering during the interferogram processing step, which is determined by the "wavelength" parameter.
