### ISSUE TITLE
Issue with PyGMTSAR installation 

### ISSUE THREAD

**Issue by NMoghaddam** [mobigroup/gmtsar#57]
**Describe the bug**
I attempted to run the notebook for SBAS and PS comparison for a stack of SAR images that was recently developed and surprisingly I keep getting this error message when trying to install PyGMTSAR:
![image](https://github.com/mobigroup/gmtsar/assets/43155679/830059b5-5743-4bda-8832-d811ba0d2ccf)
![image](https://github.com/mobigroup/gmtsar/assets/43155679/3f2b0465-5412-406c-b7e2-7249e73eae00)

Could you please advise what might be going wrong so we cant use Pygmtsar in the notebook...
Thanks,

**To Reproduce**
Steps to reproduce the behaviour:

**Screenshots**

**System and software version:**
 - OS: Windows - Google Colab 
 - GMTSAR version:

**Processing Log**
If applicable, attach a log file from the terminal output

[Please note that if no new responses are made over six months from users, the issue will get closed. If the report involves a simple fix in the code, the change could be done quickly; if it involves developing new features, do expect them to be done over the long run. Under both cases, the report will remain open until the issue is addressed one way or another.]

**Comment by mobigroup** [comment]
Please use the recent notebooks; the issue has already been fixed. Google Colab is not a stable environment, and the system packages and Python libraries available on it can change suddenly and sometimes become incompatible. We need to maintain installation commands in the notebooks according to the current Google Colab version.

If you need to update your own notebooks, simply copy the updated PyGMTSAR installation command from the new notebook. I'm not displaying it here because it will change in future versions of the notebooks following Google Colab updates.
